### ISSUE TITLE
beds set spawn even with left click

### ISSUE THREAD

**Issue by crxyne** [Cloud-Anarchy/Issue-Tracker#11]
so i broke a bed and discovered that it told me "Bed Spawn Set!" uhh im not sure if it really set my spawn but it did say that it did and i dont think that you should be able to set your bedspawn by breaking your bed

**Comment by ghost** [comment]
if you left click it (without breaking) it sets your spawn
if you right click it you need to sleep in it to set your spawn

**Comment by nothub** [comment]
was fixed in [#49](https://github.com/Cloud-Anarchy/CloudAnarchyCore/pull/49). will be fixed on the server soon, when new plugin is deployed.
