### ISSUE TITLE
NameColor bold and italic by joindate

### ISSUE THREAD

**Issue by autowert66** [Cloud-Anarchy/Issue-Tracker#13]
I think it would be nice if Midf@gs _(Joined before 30. Dec. 2020)_ have access to the bold name color and Oldf@gs _(I don't know the date)_ should have access to bold and italic.
You could also bind some colors to the playtime.

**Comment by ghost** [comment]
forget the suggestion and just give me op already

**Comment by autowert66** [comment]
> forget the suggestion and just give me op already

Is that relevant in any way?

**Comment by ghost** [comment]
> > forget the suggestion and just give me op already
> 
> Is that relevant in any way?

exactly

**Comment by autowert66** [comment]
I guess I can close this now.

**Comment by ghost** [comment]
lol
