### ISSUE TITLE
Allow traveling below bedrock!

### ISSUE THREAD

**Issue by autowert66** [Cloud-Anarchy/Issue-Tracker#16]
### Problem
When I try to go **below Bedrock** this happens:

[![image](https://user-images.githubusercontent.com/72566626/115280785-984f8e80-a148-11eb-81f3-b15e88460fbd.png)](#)

I'd like to go below Bedrock to **fast travel** in the Nether using Elytra Flight. That would be really useful to reach far places or the World Border.

### Solution
Change the Plugins to **allow going below Bedrock**.
_Maybe with a speed limit?_

**Comment by nothub** [comment]
this is intended, implied by the warning message

**Comment by nothub** [comment]
fast travel with a speed limit is contradictory
