### ISSUE TITLE
maps not updating properly

### ISSUE THREAD

**Issue by Drasmo** [Cloud-Anarchy/Issue-Tracker#3]
![2021-01-24_01 18 27](https://user-images.githubusercontent.com/76880669/105618001-271b6c00-5de3-11eb-9c2a-78b6798544b5.png)

i made a mapart. but the map is not updating. i also made a new map but it is no solution to the problem

**Comment by nothub** [comment]
This probably has to do with anti light lag, thanks for the report!
What y level are the blocks on that are not getting updated properly?

**Comment by Drasmo** [comment]
when i stand on top of the blocks i am on lvl 65. so i guess the blocks are on lvl 64?

**Comment by nothub** [comment]
okay, sry for the wait. @Krazzzzymonkey should be back soon

**Comment by Krazzzzymonkey** [comment]
Fixed 👍
