### ISSUE TITLE
Enable riding liamas again

### ISSUE THREAD

**Issue by Lqnz** [Cloud-Anarchy/Issue-Tracker#4]
I still can't ride a liama, I think I've reported this issue multiple times to Krazzzy but the issue is still there so can you please fix it this time?

**Comment by nothub** [comment]
Yeah, sorry krazzzzy is currently not available. Imma check the problem tomorrow. Thanks for the report!

**Comment by Lqnz** [comment]
> Yeah, sorry krazzzzy is currently not available. Imma check the problem tomorrow. Thanks for the report!

No problem!

**Comment by nothub** [comment]
sry for the wait. @Krazzzzymonkey should be back soon. im sorry but i didnt really spend time on the issue yet :see_no_evil:
