### ISSUE TITLE
possible tp exception

### ISSUE THREAD

**Issue by builderanddig** [Cloud-Anarchy/Issue-Tracker#6]
to be able to tp to anyone in the spawn region when ur also in the spawn region

**Comment by J4AR** [comment]
Dumbest idea ever, its 5k blocks... Learn to walk ffs takes a minute or two at max at this point may aswell be asking for op if the game is so hard for you.

**Comment by Krazzzzymonkey** [comment]
5000 blocks is really not much,i ts legit 625 blocks in the nether.
Works as intended
