### ISSUE TITLE
Inertia Donkey Dupe

### ISSUE THREAD

**Issue by Lqnz** [Cloud-Anarchy/Issue-Tracker#8]
So I was trying to do the WWE / Inertia donkey dupe but it's a bit janky.

If I turned off Cancel Packets in Freecam on Inertia and use Freecam, The server just rubberbands me, even if I reduce the speed, it still rubberbands so can it be fixed or smth?

**Comment by ghost** [comment]
it works under correct settings
you just need to find a good timer speed etc.

**Comment by nothub** [comment]
@Lqnz can this ticket be closed?
